name: GitHub CI

on: push

jobs:
  gcc:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [9, 10, 11]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-${{ matrix.version }} pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/build"
          ctest -V

  clang:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [12, 13, 14]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-${{ matrix.version }} pkg-config
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/build"
          ctest -V
